# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-12 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lang',
            field=models.CharField(choices=[(b'fa', 'Farsi'), (b'en', 'English')], default=b'en', max_length=2, verbose_name='Language'),
        ),
    ]
