# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-12 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='display_name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='display_name_fa',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
